# Generated by Django 2.2.5 on 2019-09-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgstoreapp', '0003_auto_20190926_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='author',
            new_name='auth',
        ),
    ]
