# Generated by Django 2.2.5 on 2019-09-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgstoreapp', '0004_auto_20190926_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='auth',
            new_name='author',
        ),
    ]
