# Generated by Django 2.2.5 on 2019-09-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgstoreapp', '0006_auto_20190926_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
