# Generated by Django 2.2.5 on 2019-09-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgstoreapp', '0007_auto_20190926_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='author',
        ),
    ]
