# Generated by Django 2.2.5 on 2019-09-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imgstoreapp', '0008_remove_imageupload_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
