# Generated by Django 2.2.5 on 2019-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstoreapp', '0010_auto_20190926_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
